/* Competition features */
export const competitionFeatures = [
  { identifier: 'DNS', name: 'Did Not Start', description: 'Did Not Start' },
  { identifier: 'DNF', name: 'Did Not Finish', description: 'Did Not Finish' },
  { identifier: 'DQ', name: 'Disqualified', description: 'Disqualified' },
  { identifier: 'R', name: 'Retired from competition', description: 'Retired from competition' },
  { identifier: 'Q', name: 'Qualified by place or standard', description: 'Qualified by place (track) or standard (field)' },
  { identifier: 'q', name: 'Qualified by performance', description: 'Qualified by performance (time in timed events and rank in field events)' },
  { identifier: 'qR', name: 'Advanced to next round by Referee', description: 'Advanced to next round by Referee' },
  { identifier: 'qJ', name: 'Advanced to next round by Jury of Appeal', description: 'Advanced to next round by Jury of Appeal' },
  { identifier: '>', name: 'Bent knee', description: 'Bent knee (Race walking)' },
  { identifier: '~', name: 'Loss of contact', description: 'loss of contact (Race walking)' },
  { identifier: 'yC', name: 'Yellow Card', description: 'yellow Card' },
  { identifier: 'yRC', name: 'Second yellow Card', description: 'Second yellow Card' },
  { identifier: 'RC', name: 'Red Card', description: 'Red Card' },
  { identifier: 'Fn', name: 'False Start', description: 'False Start' },
  { identifier: 'o', name: 'Clearance', description: 'Clearance (valid trial in Height Events)' },
  { identifier: '-', name: 'Pass', description: 'Pass (passed trial in field events)' },
  { identifier: 'x', name: 'Failure', description: 'Failure (failed trial in field events)' },
  { identifier: 'NM', name: 'No Mark', description: 'No Mark' },
  { identifier: 'NH', name: 'No Height', description: 'No Height' },
  { identifier: 'h', name: 'Hand-timing', description: 'Hand-timing' },
  { identifier: 'a', name: 'Automatic timing with no hundredths of a second measured', description: 'automatic timing with no hundredths of a second measured' },
  { identifier: 'A', name: 'Performance achieved at altitude', description: 'performance achieved at altitude' },
  { identifier: 'OT', name: 'Oversized Track', description: 'Oversized Track' },
];
